### ISSUE TITLE
Create a FAQ Page on Pixel Devs Website

### ISSUE THREAD

**Issue by briangershon** [Developer-DAO/pixel-avatars#102]
## Why?

Lots of publicity from @goldzulu's twitter post (and amplified with Nader's repost) show a need for a FAQ page.

## What?

Idea is to add a static FAQ page to Pixel Devs, with an obvious link at the top of the home page.

## Which FAQs?

Marc just added probably the most important one:

> "Heads up that we may need to get more explicit with “pixel devs != genesis nft/membership”. Not sure exactly where and how to say it, but looks like we should address that. The timing of this launch coincides with our messaging about the dao opening back up unfortunately" Thread: https://discord.com/channels/883478451850473483/884980325653049367/945140811408998410

You can view replies from Twitter thread with questions being asked: https://twitter.com/developer_dao/status/1495547491881820162

Also notes from @goldzulu:

I think we can do anything quick would be good. then we think of long term "website"
with roadmaps etc
i think simple
mint price
url
questions
and what are these
what is Dev4Rev

**Comment by briangershon** [comment]
Here was another tweet I saw asking about the membership questions: https://twitter.com/ArmholeHamper/status/1495550181953187842

**Comment by rasmuscnielsen** [comment]
Merged in #106
