### ISSUE TITLE
Add `meta` tags for better link preview

### ISSUE THREAD

**Issue by with-heart** [Developer-DAO/pixel-avatars#19]
I shared the link to Pixel Avatars in Discord and it resulted in just a boring old link! If we add `meta` tags we can attach an image and a description to make it more likely others will check out the project! We implemented them for developerdao.com and you can see the difference here:

![image](https://user-images.githubusercontent.com/1954752/136868849-17a52c42-2f8c-4e7a-b26c-5cae71dc99cd.png)

https://metatags.io/ makes this really easy!

**Comment by fiigmnt** [comment]
gm! Here's the preview of meta information and info I added:
<img width="500" alt="preview" src="https://user-images.githubusercontent.com/87987106/137592422-f92f78f8-2bfe-4289-b2eb-43b18daa0088.png">

PR: https://github.com/Developer-DAO/pixel-avatars/pull/25
