### ISSUE TITLE
Can't download/save the avatar properly

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/pixel-avatars#26]
Someone in the Discord server reported that when they try to save their pixel avatar, they are not being able to save the entire avatar. Instead, they are being able to save only one part of the avatar at once. (eg. pants) Link to the message: https://discord.com/channels/883478451850473483/883482557809852416/899139138396258374

This has probably got to do with the fact that we are just placing PNGs for different parts of the avatar on top of each other. But we should definitely add a download functionality.

**Comment by kavimaluskam** [comment]
I think it's also good to have a "share" function to allow directly sharing to twitter / something?

**Comment by kavimaluskam** [comment]
I did a very quick research on this issue and find a below proposal:

https://github.com/lukechilds/merge-images

```js
function downloadAvatar() {
    mergeImages(layers.value)
        .then(b64 => {
            const element = document.createElement("a");
            element.href = b64
            element.download = "image.jpg";
            element.click();
        });
}
```

Yet it's not working due to the different part of traits have different dimension:
- 3659 × 4734
- 878 × 1136

Like to ask why the trails image are of different (and quite a large) dimension?

**Comment by Dhaiwat10** [comment]
Not sure about that, @kavimaluskam. Thanks for that code snippet, tho!

Raz on Discord has also suggested a fix by using a `<canvas>`: https://discord.com/channels/883478451850473483/883482557809852416/899396611392823326

**Comment by kavimaluskam** [comment]
I am trying to modify the rendering method to canvas directly as below:

```js
<script setup>
import { onMounted } from "@vue/runtime-core"

const props = defineProps({
    state: Object
})
const updateAvatar = (width = 448, height = 580) => {
    const canvas = document.getElementById('avatar')
    const ctx = canvas.getContext("2d");
    canvas.width = width;
    canvas.height = height;

    const images = props.state.layers.value.map(layer => new Promise((resolve, reject) => {
        var image = new Image(width, height);
        image.onerror = () => reject(new Error('Couldn\'t load image'));
        image.onload = () => resolve(Object.assign(image));
        image.src = layer;
    }));

    Promise.all(images).then(images => {
        images.forEach(image => {
            ctx.drawImage(image, 0, 0, width, height)
        })
    });
}
onMounted(() => { updateAvatar() })

</script>

<template>
    <div>
        <canvas id="avatar"></canvas>
    </div>
</template>
```
Its working now, but only when mounted...
Sorry that I am not very familiar with vue, is there any API so i can trigger the `updateAvatar()` when props changes?

**Comment by Dhaiwat10** [comment]
Thanks for this @kavimaluskam! I'm not familiar with Vue myself either. @rasmuscnielsen could you help us out here haha

**Comment by rasmuscnielsen** [comment]
@kavimaluskam 

Yeah so it's very much been a moving target as things changes and the project progresses. 

The idea with the flexible traits were initially to test out the different layers of the designs, and secondly it could present a future possibility of selling tailored avatars to the public. I guess we have really discussed these options through yet.

> And if it's the case, I wonder if we can close the current issue, and image download / share (share should be more important) function, which shall be solved when the team has implemented web3 functionality?

Yeah I think that sounds good! Do you have any suggestions for how this share function could work? 

Should it just be the URL to the JPG, or a special landing page with social preview, where we host some more information and call-2-action for people to mint their own (?)
Just throwing some ideas around, haven't really thought it through :-)

**Comment by CastilloLuis** [comment]
hey any update on this? i can jump-in and help :)

**Comment by CastilloLuis** [comment]
I made a fix:
- Convert to Canvas
- Update on each prop.state change (when the user types a diff token ID)
- Download as PNG (easy because its a canvas)
- Save image as: {tokenID}.png

**Comment by Dhaiwat10** [comment]
@CastilloLuis yes, please put in a PR!

**Comment by kavimaluskam** [comment]
I think pre the above discussion we don't want to have this feature now since the team is going to generate JPG for all avatar now? @rasmuscnielsen @Dhaiwat10 ? Please correct me if I am confused again.

**Comment by Dhaiwat10** [comment]
@kavimaluskam oh sorry, I missed the discussion in-between. I'll leave the decision upto you and @rasmuscnielsen :)

**Comment by CastilloLuis** [comment]
I'll stay tuned to any final decision before submitting the PR @kavimaluskam @rasmuscnielsen

**Comment by rasmuscnielsen** [comment]
Yeah I think we can pick this one back up once the web3 integration is in place. We already have all the PNG's generated, so we just need to make a share functionality for the owned tokens once minted :-)

**Comment by rasmuscnielsen** [comment]
Just created #65 which relates to this. Since this only relates to avatars that are already claimed, it should be possible to just grab the IPFS url out of the contract and add a download function that reads from IPFS
