### ISSUE TITLE
Add support for query params

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/pixel-avatars#27]
## Feature requests
- Support query params. Eg. www.pixel-avatars.developerdao.com/?id=5350 should directly display the avatar for the token with ID=5350. The DAO's main website serves as the perfect example - https://www.developerdao.com/?id=5350.
- Sync ID input with the URL in the addressbar. Eg. if you type in a token ID at www.developerdao.com, you will notice that the URL in the addressbar syncs with your input. This lets people easily share a link to their avatars.

**Comment by carlomigueldy** [comment]
Created a PR @Dhaiwat10 https://github.com/Developer-DAO/pixel-avatars/pull/28
