### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by carlomigueldy** [Developer-DAO/pixel-avatars#29]
Would be great to maintain a codebase written on TypeScript and leverage on [Hardhat's Typechain](https://hardhat.org/plugins/typechain-hardhat.html) where it auto-generates TypeScript typings for the smart contracts that gets compiled and deployed locally. Also TypeScript would be awesome too when we're creating those tests in Chai.

If you guys would approve then I'll take a look and find a way to migrate everything into TypeScript.

**Comment by carlomigueldy** [comment]
I'm thinking of adding both! @rasmuscnielsen 

It's very convenient to have TypeScript auto generate the smart contract types.

**Comment by carlomigueldy** [comment]
Hey that sounds good too! I will reach out to him and see how we'll able to figure out adding TypeScript support without that much work. Thanks for the heads up!

Also if we add TypeScript it's basically going to be ES6 on steroids 😉  it'll be lots of fun for you, and of course if you're struggling with something on TypeScript just let us know and we'll help you out. I know TypeScript is a bit difficult to get started with.

I'll keep that in mind regarding that PR so it doesn't break so much of whatever merge conflict problems it may be.

**Comment by rasmuscnielsen** [comment]
Since the PR is merged I'll go ahead and close this. Feel free to re-open in case there are still things that needs to be addressed :-)
