### ISSUE TITLE
backgrounds

### ISSUE THREAD

**Issue by eknobl** [Developer-DAO/pixel-avatars#3]
![background-blue](https://user-images.githubusercontent.com/51840990/133120337-84e6a624-4f58-42ba-8733-1ac9d4b39d71.png)
![background-gray](https://user-images.githubusercontent.com/51840990/133120384-3e1cb709-3910-4aef-b62f-88628beb54ea.png)
![background-green](https://user-images.githubusercontent.com/51840990/133120409-f3d30200-9545-49e5-9ae9-be5844d702e8.png)
![background-orange](https://user-images.githubusercontent.com/51840990/133120422-49d28487-5e43-4a03-be26-e43268e33ed9.png)
![background-pink](https://user-images.githubusercontent.com/51840990/133120433-d6de3017-e477-4574-8647-d0d223253716.png)
![background-purple](https://user-images.githubusercontent.com/51840990/133120443-8b64e39b-dfa1-4bcf-bd46-66bd32d9ccfd.png)
![background-yellow](https://user-images.githubusercontent.com/51840990/133120458-3e6f9eee-4f94-437c-91e1-9ef8efbb6f24.png)

**Comment by goldzulu** [comment]
No longer relevant
