### ISSUE TITLE
Add test(s) for smart contract

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/pixel-avatars#30]
#23 added the foundation for the smart contract's source code. Would be a good idea to have some tests in place since we probably will iterate on the contract.

**Comment by carlomigueldy** [comment]
👀 I want to add tests with TypeScript, soon I'll add some and create a PR

**Comment by gjsyme** [comment]
I see that pixel-avatars.spec.ts has been created and the vscode plugin says it was `9869201` by @carlomigueldy so I'm thinking you may want to close this or call out any additional tests desired.
