### ISSUE TITLE
Convert included contracts in solidity smart contract into import dependencies

### ISSUE THREAD

**Issue by goldzulu** [Developer-DAO/pixel-avatars#33]
Convert included contracts into import dependencies.
as per kevincharm (discord) 
- install dependencies (openzeppelin etc) with npm and import them. 
-> benefits - it will be more easily readable, and hardhat can output 1 file for etherscan verification.

**Comment by carlomigueldy** [comment]
This issue can be closed, already integrated

**Comment by goldzulu** [comment]
Closing
