### ISSUE TITLE
Use ethers.js instead of web3 for frontend code

### ISSUE THREAD

**Issue by goldzulu** [Developer-DAO/pixel-avatars#34]
to be consistently using ethers.js for front end since already using it on the hardhat side

**Comment by AlexNi245** [comment]
I would start working on this one, before i implement the actual contract call

**Comment by gjsyme** [comment]
This issues looks to be done (merged, I can't find web3 in the package.json files (but it is a dependency of dev dependencies))

**Comment by rasmuscnielsen** [comment]
Closing as we're using ethers now 👍
