### ISSUE TITLE
Write an article about obtaining MATIC for launch

### ISSUE THREAD

**Issue by briangershon** [Developer-DAO/pixel-avatars#83]
For DAO members to mint their token, then need MATIC! And there are many steps involved and added expense.

We need to write an article that provides the best/cheapest/least-friction way to obtain Polygon MATIC.

One idea is using https://www.kraken.com/en-us/

**Comment by briangershon** [comment]
Thanks @sven-so for the info!

**Comment by sven-so** [comment]
Just found out, 
Binance can send directly to matic. 

![image](https://user-images.githubusercontent.com/1716655/152497876-e8187e37-0550-4b99-9235-f1889b160e77.png)

**Comment by briangershon** [comment]
I was also curious about MoonPay since they are in various wallets.

Interestingly, they don't offer direct MATIC in the U.S. -- looks like it's similar to Coinbase and only supports MATIC via Ethereum. But non-US can buy Matic directly.

https://support.moonpay.com/hc/en-gb/articles/360009280177-Which-cryptocurrencies-do-you-support-

**Comment by briangershon** [comment]
I wonder if buying Eth and swapping may be the easiest?

I ran across this posted in Discord ([thread](https://discord.com/channels/883478451850473483/912005647896313867/929464965478350938)) that mentioned:

- https://wallet.polygon.technology
- Matcha (https://matcha.xyz/)
- CowSwap (https://cowswap.exchange/#/swap)

There are a list of bridges from the polygon site too: https://wallet.polygon.technology/fast-withdraw

**Comment by briangershon** [comment]
## Pay Dirt

Ok, I think I found the best article so far: [How to Get MATIC on Polygon: A Step-by-Step Guide](https://medium.com/prepo/setting-up-metamask-and-getting-eth-matic-on-polygon-step-by-step-guide-fd55147a0f05)

Other articles:
- I've also seen the terms WETH, WMATIC, MATIC. [What is WMATIC?](https://quickswap-layer2.medium.com/i-know-what-matic-is-but-what-tf-is-wmatic-ba7b3220e36f)

**Comment by briangershon** [comment]
And to keep it interesting, I've found the terminology seems different with each site: WETH, WMATIC, MATIC, "ETH — Ethereum (Polygon)", "USDC on the Polygon network", "ETH Polygon" :-)

Opensea has a guide too: <https://support.opensea.io/hc/en-us/articles/1500012881642-How-do-I-transfer-ETH-from-Ethereum-to-Polygon-> but I think this is wrapped MATIC?

**Comment by rasmuscnielsen** [comment]
Cool @briangershon ! Lots of great resources.

So far these seems the most attractive to me (non-us):

- Binance 
- Transak
- Moonpay

The article you sent didn't mention prices for transak and moonpay though. Do you know how much these charge in fees? 
I seem to recall transak was 3-4% plus a minimum fee last I used it although that was for Ethereum so perhaps different scenario altogether.

**Comment by briangershon** [comment]
Another interesting method: https://medium.com/@CryptoCruisers/metamask-nft-guide-how-to-buy-matic-for-the-polygon-network-with-no-gas-fees-1236f653ed1e

**Comment by briangershon** [comment]
I'm summarizing this over in a new Wiki page here: https://github.com/Developer-DAO/pixel-avatars/wiki/Polygon-MATIC

**Comment by briangershon** [comment]
Another recent mention:

"buy LTC (Litecoin) on Kraken where I have EUR sitting, withdraw that to Binance, convert to MATIC and then withdraw to wallet. I found LTC is among the cheapest transaction and withdrawal fees all across, so great for transfer."
